### ISSUE TITLE
The Geo input is having issues rendering

### ISSUE THREAD

**Issue by andrewkfiedler** [codice/ddf-ui#98]
<img width="709" alt="Screen Shot 2020-02-14 at 7 00 20 PM" src="https://user-images.githubusercontent.com/11984853/74675278-6f142680-5170-11ea-99ae-d080fa959deb.png">
<img width="576" alt="Screen Shot 2020-02-14 at 6 57 00 PM" src="https://user-images.githubusercontent.com/11984853/74675281-70455380-5170-11ea-9bce-1d262933848f.png">

**Comment by maiiiiiiii** [comment]
Also broken:
**Line:** Form and not able to draw
**Polygon:** Form and not able to draw
**Point-Radius:** Lat/Lon (DD) and not able to draw, Lat/Lon (DMS) and not able to draw, USNG/MGRS  and not able to draw, UTM /UPS and not able to draw
**Bounding Box:** Lat/Lon )DD, Lat/Lon DMS and able to draw but values not capture in w/s/e/n fields, USNG/MGRS
